# Generated by Django 5.0 on 2024-01-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SEOReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="SEO", max_length=100, verbose_name="Название"
                    ),
                ),
                (
                    "visits",
                    models.PositiveIntegerField(default=0, verbose_name="Визиты"),
                ),
                (
                    "all_expense",
                    models.PositiveIntegerField(default=0, verbose_name="Расход"),
                ),
                (
                    "sum_transactions",
                    models.PositiveIntegerField(default=0, verbose_name="Заявки"),
                ),
                (
                    "avg_check",
                    models.PositiveIntegerField(default=0, verbose_name="Средний чек"),
                ),
                (
                    "income",
                    models.PositiveIntegerField(default=0, verbose_name="Доход"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "SEO отчет",
                "verbose_name_plural": "SEO отчеты",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="statistics__created_e69005_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SEOReportDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="-----", max_length=100, verbose_name="Название"
                    ),
                ),
                (
                    "visits",
                    models.PositiveIntegerField(default=0, verbose_name="Визиты"),
                ),
                (
                    "impressions",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Показы"
                    ),
                ),
                (
                    "ctr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="CTR",
                    ),
                ),
                (
                    "avg_position",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Средняя позиция",
                    ),
                ),
                (
                    "convert",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Средняя позиция",
                    ),
                ),
                (
                    "transactions",
                    models.PositiveIntegerField(default=0, verbose_name="Заявки"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="statistics_and_analytics.seoreport",
                        verbose_name="Канал трафика",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="statistics__created_10090d_idx"
                    )
                ],
            },
        ),
    ]
