# Generated by Django 5.0 on 2024-01-01 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistics_and_analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectSEOReport",
            fields=[
                (
                    "seoreportdetail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="statistics_and_analytics.seoreportdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Прямые заходы отчет",
                "verbose_name_plural": "SEO Прямые заход отчеты",
                "ordering": ["-created"],
            },
            bases=("statistics_and_analytics.seoreportdetail",),
        ),
        migrations.CreateModel(
            name="GoogleSEOReport",
            fields=[
                (
                    "seoreportdetail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="statistics_and_analytics.seoreportdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Google отчет",
                "verbose_name_plural": "SEO Google отчеты",
                "ordering": ["-created"],
            },
            bases=("statistics_and_analytics.seoreportdetail",),
        ),
        migrations.CreateModel(
            name="ReferralsSEOReport",
            fields=[
                (
                    "seoreportdetail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="statistics_and_analytics.seoreportdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Ссылочные заходы отчет",
                "verbose_name_plural": "SEO Ссылочные заход отчеты",
                "ordering": ["-created"],
            },
            bases=("statistics_and_analytics.seoreportdetail",),
        ),
        migrations.CreateModel(
            name="YandexSEOReport",
            fields=[
                (
                    "seoreportdetail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="statistics_and_analytics.seoreportdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Яндекс отчет",
                "verbose_name_plural": "SEO Яндекс отчеты",
                "ordering": ["-created"],
            },
            bases=("statistics_and_analytics.seoreportdetail",),
        ),
        migrations.AlterModelOptions(
            name="seoreportdetail",
            options={
                "ordering": ["-created"],
                "verbose_name": "SEO отчет детально",
                "verbose_name_plural": "SEO отчеты детально",
            },
        ),
    ]
