# Generated by Django 5.0 on 2024-01-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "statistics_and_analytics",
            "0002_directseoreport_googleseoreport_referralsseoreport_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="directseoreport",
            options={
                "ordering": ["-created"],
                "verbose_name": "SEO Прямые заходы отчет",
                "verbose_name_plural": "SEO Прямые заходы отчеты",
            },
        ),
        migrations.AlterModelOptions(
            name="referralsseoreport",
            options={
                "ordering": ["-created"],
                "verbose_name": "SEO Ссылочные заходы отчет",
                "verbose_name_plural": "SEO Ссылочные заходы отчеты",
            },
        ),
        migrations.AlterField(
            model_name="seoreportdetail",
            name="convert",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0,
                max_digits=15,
                null=True,
                verbose_name="Конверсия",
            ),
        ),
    ]
