# Generated by Django 5.0 on 2024-01-01 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistics_and_analytics", "0003_alter_directseoreport_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="-----", max_length=100, verbose_name="Название"
                    ),
                ),
                (
                    "average_check",
                    models.PositiveIntegerField(default=0, verbose_name="Средний чек"),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="Показы"),
                ),
                (
                    "visits",
                    models.PositiveIntegerField(default=0, verbose_name="Визиты"),
                ),
                (
                    "ctr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="CTR",
                    ),
                ),
                (
                    "cta",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Стоимость клика"
                    ),
                ),
                (
                    "transactions",
                    models.PositiveIntegerField(default=0, verbose_name="Заявки"),
                ),
                (
                    "all_expense",
                    models.PositiveIntegerField(default=0, verbose_name="Расход"),
                ),
                (
                    "income",
                    models.PositiveIntegerField(default=0, verbose_name="Доход"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="FacebookAds",
            fields=[
                (
                    "ads_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="statistics_and_analytics.ads",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facebook Ads отчет",
                "verbose_name_plural": "Facebook Ads отчеты",
            },
            bases=("statistics_and_analytics.ads",),
        ),
        migrations.CreateModel(
            name="GoogleAds",
            fields=[
                (
                    "ads_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="statistics_and_analytics.ads",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Ads отчет",
                "verbose_name_plural": "Google Ads отчеты",
            },
            bases=("statistics_and_analytics.ads",),
        ),
        migrations.CreateModel(
            name="InstagramAds",
            fields=[
                (
                    "ads_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="statistics_and_analytics.ads",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram Ads отчет",
                "verbose_name_plural": "Instagram Ads отчеты",
            },
            bases=("statistics_and_analytics.ads",),
        ),
        migrations.CreateModel(
            name="MyTarget",
            fields=[
                (
                    "ads_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="statistics_and_analytics.ads",
                    ),
                ),
            ],
            options={
                "verbose_name": "MyTarget Ads отчет",
                "verbose_name_plural": "MyTarget Ads отчеты",
            },
            bases=("statistics_and_analytics.ads",),
        ),
        migrations.CreateModel(
            name="VKAds",
            fields=[
                (
                    "ads_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="statistics_and_analytics.ads",
                    ),
                ),
            ],
            options={
                "verbose_name": "VK Ads отчет",
                "verbose_name_plural": "VK Ads отчеты",
            },
            bases=("statistics_and_analytics.ads",),
        ),
        migrations.CreateModel(
            name="YandexDirect",
            fields=[
                (
                    "ads_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="statistics_and_analytics.ads",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yandex Direct отчет",
                "verbose_name_plural": "Yandex Direct отчеты",
            },
            bases=("statistics_and_analytics.ads",),
        ),
        migrations.AddIndex(
            model_name="ads",
            index=models.Index(
                fields=["-created"], name="statistics__created_01a78e_idx"
            ),
        ),
    ]
