# Generated by Django 5.0 on 2024-01-01 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "statistics_and_analytics",
            "0004_ads_facebookads_googleads_instagramads_mytarget_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherAds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="-----", max_length=100, verbose_name="Название"
                    ),
                ),
                (
                    "visits",
                    models.PositiveIntegerField(default=0, verbose_name="Визиты"),
                ),
                (
                    "transactions",
                    models.PositiveIntegerField(default=0, verbose_name="Заявки"),
                ),
                (
                    "all_expense",
                    models.PositiveIntegerField(default=0, verbose_name="Расход"),
                ),
                (
                    "income",
                    models.PositiveIntegerField(default=0, verbose_name="Доход"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="CallTracking",
            fields=[
                (
                    "otherads_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="statistics_and_analytics.otherads",
                    ),
                ),
            ],
            options={
                "verbose_name": "CallTracking отчет",
                "verbose_name_plural": "CallTracking отчеты",
            },
            bases=("statistics_and_analytics.otherads",),
        ),
        migrations.CreateModel(
            name="EmailTracking",
            fields=[
                (
                    "otherads_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="statistics_and_analytics.otherads",
                    ),
                ),
            ],
            options={
                "verbose_name": "EmailTracking отчет",
                "verbose_name_plural": "EmailTracking отчеты",
            },
            bases=("statistics_and_analytics.otherads",),
        ),
        migrations.CreateModel(
            name="TelegramAds",
            fields=[
                (
                    "otherads_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="statistics_and_analytics.otherads",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Ads отчет",
                "verbose_name_plural": "Telegram Ads отчеты",
            },
            bases=("statistics_and_analytics.otherads",),
        ),
        migrations.AddIndex(
            model_name="otherads",
            index=models.Index(
                fields=["-created"], name="statistics__created_483f20_idx"
            ),
        ),
    ]
