# Generated by Django 5.0 on 2024-01-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "statistics_and_analytics",
            "0005_otherads_calltracking_emailtracking_telegramads_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="otherads",
            name="convert",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0,
                max_digits=15,
                null=True,
                verbose_name="Конверсия",
            ),
        ),
    ]
