# Generated by Django 5.0 on 2024-01-01 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("statistics_and_analytics", "0006_otherads_convert"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seoreport",
            old_name="sum_transactions",
            new_name="transactions",
        ),
    ]
